FORMAT: 1A

# Huddle API
You can put some description here.

# Group Company

## Company

## Company Manager

# Group Discussion

## Discussion Post

# Group Document

## Document

## Approval

## Lock

# Group Folder

## Folder [/files/folders/{folderId}]
A folder is used to organise, group, and protect documents that are stored in Huddle.

+ Parameters

    + folderId (number, `1`) ... A unique identifier for the folder.

### Retrieve a Folder [GET]

+ Request (application/vnd.huddle.data+xml)

    + Headers
    
            If-Modified-Since: Sat, 29 Oct 2012 19:43:31 GMT

+ Response 200 (application/vnd.huddle.data+xml)

    + Headers
    
            Last-Modified: Wed, 18 Jun 2014 14:09:40 GMT
            
    + Body
    
            { 
                "owner": { 
                    "name": "Bob Smith",
                    "email": "bob.smith@acme.com",
                    "rel": "owner",
                    "links": [ { 
                        "rel": "self",
                        "href": "https://api.huddle.net/users/45"
                    }, { 
                        "rel": "avatar",
                        "href": "https://api.huddle.net/files/users/45/avatar?h=abc"
                    }, { 
                        "rel": "alternate",
                        "href": "https://my.huddle.net/user/bsmith",
                        "type": "text/html"
                    } ]
                },
                "folders": [ ],
                "documents": [ ],
                "created": "Wed, 18 Jun 2014 14:26:16 GMT",
                "permissionsSummary": { 
                    "owner": { 
                        "name": "Bob Smith",
                        "email": "bob.smith@acme.com",
                        "rel": "owner",
                        "links": [ { 
                            "rel": "self",
                            "href": "https://api.huddle.net/users/45"
                        }, { 
                            "rel": "avatar",
                            "href": "https://api.huddle.net/files/users/45/avatar?h=abc"
                        }, { 
                            "rel": "alternate",
                            "href": "https://my.huddle.net/user/bsmith",
                            "type": "text/html"
                        } ]
                    },
                    "actorPermissions": { 
                        "actor": { 
                            "name": "Bob Smith",
                            "email": "bob.smith@acme.com",
                            "rel": "currentUser",
                            "links": [ { 
                                "rel": "self",
                                "href": "https://api.huddle.net/users/45"
                            }, { 
                                "rel": "avatar",
                                "href": "https://api.huddle.net/files/users/45/avatar?h=abc"
                            }, { 
                                "rel": "alternate",
                                "href": "https://my.huddle.net/user/bsmith",
                                "type": "text/html"
                            } ]
                        },
                        "permissions": [ { 
                            "type": "Read"
                        }, { 
                            "type": "Edit"
                        } ]
                    },
                    "links": [ { 
                        "rel": "self",
                        "href": "https://api.huddle.net/files/folders/96/permissions"
                    } ],
                    "teams": [ { 
                        "links": [ { 
                            "rel": "self",
                            "href": "https://api.huddle.net/teams/-1"
                        } ],
                        "members": [ ],
                        "title": "Default Permissions Group",
                        "type": "default",
                        "permissions": [ { 
                            "type": "Read"
                        }, { 
                            "type": "Edit"
                        } ],
                        "parentPermissions": [ { 
                            "type": "Read"
                        }, { 
                            "type": "Edit"
                        } ]
                    }, { 
                        "links": [ { 
                            "rel": "self",
                            "href": "https://api.huddle.net/teams/13"
                        } ],
                        "members": [ { 
                            "name": "Bob Smith",
                            "email": "bob.smith@acme.com",
                            "rel": "members",
                            "links": [ { 
                                "rel": "self",
                                "href": "https://api.huddle.net/users/45"
                            }, { 
                                "rel": "avatar",
                                "href": "https://api.huddle.net/files/users/45/avatar?h=abc"
                            }, { 
                                "rel": "alternate",
                                "href": "https://my.huddle.net/user/bsmith",
                                "type": "text/html"
                            } ]
                        } ],
                        "title": "Team A",
                        "type": "members",
                        "permissions": [ { 
                            "type": "Read"
                        }, { 
                            "type": "Edit"
                        } ],
                        "parentPermissions": [ { 
                            "type": "Read"
                        }, { 
                            "type": "Edit"
                        } ]
                    }, { 
                        "links": [ { 
                            "rel": "self",
                            "href": "https://api.huddle.net/workspaces/75/managers"
                        } ],
                        "members": [ { 
                            "name": "Bob Smith",
                            "email": "bob.smith@acme.com",
                            "rel": "manager",
                            "links": [ { 
                                "rel": "self",
                                "href": "https://api.huddle.net/users/45"
                            }, { 
                                "rel": "avatar",
                                "href": "https://api.huddle.net/files/users/45/avatar?h=abc"
                            }, { 
                                "rel": "alternate",
                                "href": "https://my.huddle.net/user/bsmith",
                                "type": "text/html"
                            } ]
                        } ],
                        "title": "Workspace Managers",
                        "type": "managers",
                        "permissions": [ { 
                            "type": "Read"
                        }, { 
                            "type": "Edit"
                        } ],
                        "parentPermissions": [ { 
                            "type": "Read"
                        }, { 
                            "type": "Edit"
                        } ]
                    } ],
                    "restricted": true
                },
                "ancestry": [ { 
                    "links": [ { 
                        "rel": "self",
                        "href": "https://api.huddle.net/files/folders/852"
                    } ],
                    "title": "Videos"
                } ],
                "links": [ { 
                    "rel": "create-document",
                    "href": "https://api.huddle.net/files/folders/96/documents"
                }, { 
                    "rel": "create-folder",
                    "href": "https://api.huddle.net/files/folders/96"
                }, { 
                    "rel": "delete",
                    "href": "https://api.huddle.net/files/folders/96"
                }, { 
                    "rel": "self",
                    "href": "https://api.huddle.net/files/folders/96"
                }, { 
                    "rel": "permissions",
                    "href": "https://api.huddle.net/files/folders/96/permissions"
                }, { 
                    "rel": "workspace-summary",
                    "href": "https://api.huddle.net/workspaces/75"
                }, { 
                    "rel": "share",
                    "href": "https://api.huddle.net/files/folders/96/share"
                }, { 
                    "rel": "bulk-delete",
                    "href": "https://api.huddle.net/files/bulkprocess/delete"
                }, { 
                    "rel": "bulk-move",
                    "href": "https://api.huddle.net/files/bulkprocess/move"
                }, { 
                    "rel": "bulk-download",
                    "href": "https://api.huddle.net/files/bulkprocess/download"
                }, { 
                    "rel": "document-library-settings",
                    "href": "https://api.huddle.net/files/workspaces/75/folders/root/settings"
                }, { 
                    "rel": "edit",
                    "href": "https://api.huddle.net/files/folders/96/edit"
                }, { 
                    "rel": "editPermissions",
                    "href": "https://api.huddle.net/files/folders/96/permissions"
                }, { 
                    "rel": "move",
                    "href": "https://api.huddle.net/files/folders/96/edit"
                }, { 
                    "rel": "copy",
                    "href": "https://api.huddle.net/files/folders/96/copy"
                }, { 
                    "rel": "parent",
                    "href": "https://api.huddle.net/files/folders/852"
                } ],
                "title": "Projects",
                "displayName": "Projects",
                "description": "Store project-related documents here",
                "updated": "Wed, 18 Jun 2014 14:26:16 GMT"
            }

### Delete a folder [DELETE]

+ Response 200 (application/vnd.huddle.data+xml)

    + Headers
    
            Link: </files/folders/{folderId}>;rel="parent"
            
## Document Library Settings  [/files/workspaces/{workspaceId}/folders/root/settings]
      
# Group Notification

## Notifications Collection

# Group Workspace

## Workspace

## Workspace Changes