FORMAT: 1A

# Huddle API
Hello, this is Huddle's API.

# Group Companies

## Company  [/people/companies/{companyId}]

### Retrieve a Company [GET]

+ Response 200 (application/vnd.huddle.data+xml)

## Company List  [/people/companies]

### Retrieve all Companies [GET]

+ Response 200 (application/vnd.huddle.data+xml)

## Company Manager [/people/companies/{companyId}/managers/{memberId}]

### Demote a Member from Manager [DELETE]

+ Response 204 (application/vnd.huddle.data+xml)

## Company Manager List [/people/companies/{companyId}/managers]

### Promote a Member to Manager [POST]

+ Response 201 (application/vnd.huddle.data+xml)

## Company Member List [/people/companies/{companyId}/members]

### Retrieve a list of Members for a Company [GET]

+ Response 200 (application/vnd.huddle.data+xml)

## Company Member [/people/companies/{companyId}/members/{memberId}]

### Delete a Company Member [DELETE]

+ Response 204 (application/vnd.huddle.data+xml)

# Group Documents

## Document [/files/documents/{documentId}]

### Retrieve a Document [GET]

+ Response 200 (application/vnd.huddle.data+xml)

### Delete a Document [DELETE]

+ Response 200 (application/vnd.huddle.data+xml)

## Document Content [/files/documents/{documentId}/content]

### Download a Document's Content [GET]

+ Response 200 (application/vnd.huddle.data+xml)

## Document Edit [/files/documents/{documentId}/edit]

### Update or Move a Document [POST]

+ Response 202 (application/vnd.huddle.data+xml)

## Document Version List [/files/documents/{documentId}/version]

### Create a Document Version [POST]

+ Response 201 (application/vnd.huddle.data+xml)

## Document Version Thumbnail Content [/files/documents/{documentId}/versions/{versionId}/thumbnails/medium/content]

### Download a Document Version Thumbnail's Content [POST]

+ Response 200 (application/vnd.huddle.data+xml)

## Document Restore [/files/documents/{documentId}/restore]

### Restore a Document [PUT]

+ Response 204 (application/vnd.huddle.data+xml)

## Document Copy [/files/documents/{documentId}/copy]

### Create a Document Copy [POST]

+ Response 201 (application/vnd.huddle.data+xml)

## Document Approval List [/files/documents/{documentId}/approvals]

### Retrieve a Document Approval Approval List for a Document [GET]

+ Response 200 (application/vnd.huddle.data+xml)

## Document Approval Due Date Update [/files/documents/{documentId}/approvals/updateduedate]

### Update a Document Approval's Details [POST]

+ Response 200 (application/vnd.huddle.data+xml)

## Document Approval Assignee Update [/files/documents/{documentId}/approvals/updateassignees]

### Update a Document Approval's Assignee List [POST]

+ Response 200 (application/vnd.huddle.data+xml)

## Document Approval Request [/files/documents/{documentId}/approvals/request]

### Request a Document Approval [POST]

+ Response 200 (application/vnd.huddle.data+xml)

## Document Approval Assignment [/files/documents/{documentId}/approvals/assignment]

### Update a Document Approval Assignment Status [POST]

+ Response 200 (application/vnd.huddle.data+xml)

## Lock [/files/documents/{documentId}/lock]

# Group Folders

## Folder [/files/folders/{folderId}]
A folder is used to organise, group, and protect documents that are stored in Huddle.

+ Parameters

    + folderId (number, `1`) ... A unique identifier for the folder.

### Retrieve a Folder [GET]

+ Request (application/vnd.huddle.data+xml)

    + Headers
    
            If-Modified-Since: Sat, 29 Oct 2012 19:43:31 GMT

+ Response 200 (application/vnd.huddle.data+xml)

    + Headers
    
            Last-Modified: Wed, 18 Jun 2014 14:09:40 GMT
            
    + Body
    
            { 
                "owner": { 
                    "name": "Bob Smith",
                    "email": "bob.smith@acme.com",
                    "rel": "owner",
                    "links": [ { 
                        "rel": "self",
                        "href": "https://api.huddle.net/users/45"
                    }, { 
                        "rel": "avatar",
                        "href": "https://api.huddle.net/files/users/45/avatar?h=abc"
                    }, { 
                        "rel": "alternate",
                        "href": "https://my.huddle.net/user/bsmith",
                        "type": "text/html"
                    } ]
                },
                "folders": [ ],
                "documents": [ ],
                "created": "Wed, 18 Jun 2014 14:26:16 GMT",
                "permissionsSummary": { 
                    "owner": { 
                        "name": "Bob Smith",
                        "email": "bob.smith@acme.com",
                        "rel": "owner",
                        "links": [ { 
                            "rel": "self",
                            "href": "https://api.huddle.net/users/45"
                        }, { 
                            "rel": "avatar",
                            "href": "https://api.huddle.net/files/users/45/avatar?h=abc"
                        }, { 
                            "rel": "alternate",
                            "href": "https://my.huddle.net/user/bsmith",
                            "type": "text/html"
                        } ]
                    },
                    "actorPermissions": { 
                        "actor": { 
                            "name": "Bob Smith",
                            "email": "bob.smith@acme.com",
                            "rel": "currentUser",
                            "links": [ { 
                                "rel": "self",
                                "href": "https://api.huddle.net/users/45"
                            }, { 
                                "rel": "avatar",
                                "href": "https://api.huddle.net/files/users/45/avatar?h=abc"
                            }, { 
                                "rel": "alternate",
                                "href": "https://my.huddle.net/user/bsmith",
                                "type": "text/html"
                            } ]
                        },
                        "permissions": [ { 
                            "type": "Read"
                        }, { 
                            "type": "Edit"
                        } ]
                    },
                    "links": [ { 
                        "rel": "self",
                        "href": "https://api.huddle.net/files/folders/96/permissions"
                    } ],
                    "teams": [ { 
                        "links": [ { 
                            "rel": "self",
                            "href": "https://api.huddle.net/teams/-1"
                        } ],
                        "members": [ ],
                        "title": "Default Permissions Group",
                        "type": "default",
                        "permissions": [ { 
                            "type": "Read"
                        }, { 
                            "type": "Edit"
                        } ],
                        "parentPermissions": [ { 
                            "type": "Read"
                        }, { 
                            "type": "Edit"
                        } ]
                    }, { 
                        "links": [ { 
                            "rel": "self",
                            "href": "https://api.huddle.net/teams/13"
                        } ],
                        "members": [ { 
                            "name": "Bob Smith",
                            "email": "bob.smith@acme.com",
                            "rel": "members",
                            "links": [ { 
                                "rel": "self",
                                "href": "https://api.huddle.net/users/45"
                            }, { 
                                "rel": "avatar",
                                "href": "https://api.huddle.net/files/users/45/avatar?h=abc"
                            }, { 
                                "rel": "alternate",
                                "href": "https://my.huddle.net/user/bsmith",
                                "type": "text/html"
                            } ]
                        } ],
                        "title": "Team A",
                        "type": "members",
                        "permissions": [ { 
                            "type": "Read"
                        }, { 
                            "type": "Edit"
                        } ],
                        "parentPermissions": [ { 
                            "type": "Read"
                        }, { 
                            "type": "Edit"
                        } ]
                    }, { 
                        "links": [ { 
                            "rel": "self",
                            "href": "https://api.huddle.net/workspaces/75/managers"
                        } ],
                        "members": [ { 
                            "name": "Bob Smith",
                            "email": "bob.smith@acme.com",
                            "rel": "manager",
                            "links": [ { 
                                "rel": "self",
                                "href": "https://api.huddle.net/users/45"
                            }, { 
                                "rel": "avatar",
                                "href": "https://api.huddle.net/files/users/45/avatar?h=abc"
                            }, { 
                                "rel": "alternate",
                                "href": "https://my.huddle.net/user/bsmith",
                                "type": "text/html"
                            } ]
                        } ],
                        "title": "Workspace Managers",
                        "type": "managers",
                        "permissions": [ { 
                            "type": "Read"
                        }, { 
                            "type": "Edit"
                        } ],
                        "parentPermissions": [ { 
                            "type": "Read"
                        }, { 
                            "type": "Edit"
                        } ]
                    } ],
                    "restricted": true
                },
                "ancestry": [ { 
                    "links": [ { 
                        "rel": "self",
                        "href": "https://api.huddle.net/files/folders/852"
                    } ],
                    "title": "Videos"
                } ],
                "links": [ { 
                    "rel": "create-document",
                    "href": "https://api.huddle.net/files/folders/96/documents"
                }, { 
                    "rel": "create-folder",
                    "href": "https://api.huddle.net/files/folders/96"
                }, { 
                    "rel": "delete",
                    "href": "https://api.huddle.net/files/folders/96"
                }, { 
                    "rel": "self",
                    "href": "https://api.huddle.net/files/folders/96"
                }, { 
                    "rel": "permissions",
                    "href": "https://api.huddle.net/files/folders/96/permissions"
                }, { 
                    "rel": "workspace-summary",
                    "href": "https://api.huddle.net/workspaces/75"
                }, { 
                    "rel": "share",
                    "href": "https://api.huddle.net/files/folders/96/share"
                }, { 
                    "rel": "bulk-delete",
                    "href": "https://api.huddle.net/files/bulkprocess/delete"
                }, { 
                    "rel": "bulk-move",
                    "href": "https://api.huddle.net/files/bulkprocess/move"
                }, { 
                    "rel": "bulk-download",
                    "href": "https://api.huddle.net/files/bulkprocess/download"
                }, { 
                    "rel": "document-library-settings",
                    "href": "https://api.huddle.net/files/workspaces/75/folders/root/settings"
                }, { 
                    "rel": "edit",
                    "href": "https://api.huddle.net/files/folders/96/edit"
                }, { 
                    "rel": "editPermissions",
                    "href": "https://api.huddle.net/files/folders/96/permissions"
                }, { 
                    "rel": "move",
                    "href": "https://api.huddle.net/files/folders/96/edit"
                }, { 
                    "rel": "copy",
                    "href": "https://api.huddle.net/files/folders/96/copy"
                }, { 
                    "rel": "parent",
                    "href": "https://api.huddle.net/files/folders/852"
                } ],
                "title": "Projects",
                "displayName": "Projects",
                "description": "Store project-related documents here",
                "updated": "Wed, 18 Jun 2014 14:26:16 GMT"
            }
            
+ Response 400 (application/vnd.huddle.data+xml)

### Delete a folder [DELETE]

+ Request (application/vnd.huddle.data+json)

+ Response 200 (application/vnd.huddle.data+json)

    + Headers
    
            Link: </files/folders/{folderId}>;rel="parent"
            
## Document Library Settings  [/files/workspaces/{workspaceId}/folders/root/settings]
      
# Group Notifications

## User Notifications [/notifications/user/{userId}/received]

### Retrieve notifications for a user [GET]

+ Request (application/atom+xml)

+ Response 200 (application/atom+xml)

# Group Workspaces

## Workspace

## Workspace Changes